package models

const(
	TokenNewLine		= "NEW_LINE"
	TokenString		= "STRING"
	TokenFloat		= "FLOAT"
	TokenNumber		= "NUMBER"
	TokenBoolean		= "BOOLEAN"
	TokenControlFlow	= "CONTROL_FLOW"
	TokenIfStatement	= "IF_STATEMENT"
	TokenLoopStatement	= "LOOP_STATEMENT"
	TokenFuncStatement	= "FUNC_STATEMENT"
	TokenType		= "TYPE"
	TokenComment		= "COMMENT"
	TokenCall		= "CALL"
	TokenParentheses	= "PARENTHESES"
	TokenBinOp		= "BINARY_OP"
	TokenUnOp		= "UNARY_OP"
	TokenArrayAccess	= "ARRAY"
	TokenNull		= "NULL"
	TokenIdent		= "IDENT"
	TokenAssign		= "ASSIGN"
	TokenOperator		= "OPERATOR"
	TokenDelimiter		= "DELIMITER"
	TokenSpace		= "SPACE"
	TokenObj		= "OBJECT"
	TokenUnknown		= "UNKNOWN"
)
