package models

const(
	TokenList		= "LIST"
	TokenImport		= "IMPORT"
	TokenNewLine		= "NEW_LINE"
	TokenString		= "<str>"
	TokenFloat		= "<float>"
	TokenNumber		= "<int>"
	TokenBoolean		= "<bool>"
	TokenDynamic		= "dynamic"
	TokenModule		= "module"
	TokenControlFlow	= "CONTROL_FLOW"
	TokenIfStatement	= "IF_STATEMENT"
	TokenLoopStatement	= "LOOP_STATEMENT"
	TokenFuncStatement	= "FUNC_STATEMENT"
	TokenNativeSugar	= "NATIVE_SUGAR"
	TokenType		= "TYPE"
	TokenComment		= "COMMENT"
	TokenCall		= "CALL"
	TokenParentheses	= "PARENTHESES"
	TokenBinOp		= "BINARY_OP"
	TokenUnOp		= "UNARY_OP"
	TokenArrayAccess	= "ARRAY"
	TokenNull		= "NULL"
	TokenIdent		= "IDENT"
	TokenAssign		= "ASSIGN"
	TokenOperator		= "OPERATOR"
	TokenDelimiter		= "DELIMITER"
	TokenSpace		= "SPACE"
	TokenObj		= "OBJECT"
	TokenUnknown		= "UNKNOWN"
)
